# Generated by Django 3.2 on 2021-07-20 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_course_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='desc',
            field=models.TextField(default=' ', max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='course_name',
            field=models.CharField(max_length=500),
        ),
    ]
