# Generated by Django 3.2 on 2021-07-20 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20210720_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
