# Generated by Django 3.2 on 2021-07-21 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_lectures'),
    ]

    operations = [
        migrations.AddField(
            model_name='lectures',
            name='course_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='dashboard.course'),
            preserve_default=False,
        ),
    ]
