# Generated by Django 3.2 on 2021-05-12 05:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Accounts', '0002_auto_20210504_1101'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription_bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_type', models.CharField(choices=[('BASIC', 'BASIC'), ('ADVANCE', 'ADVANCE'), ('VIP', 'VIP'), ('PREMIUM', 'PREMIUM')], max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('datetime', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
