# Generated by Django 3.2 on 2021-05-18 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0005_auto_20210518_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricing',
            name='duration',
            field=models.CharField(choices=[('mo', 'month'), ('yr', 'year')], default='', max_length=50),
            preserve_default=False,
        ),
    ]
