# Generated by Django 3.2 on 2021-05-26 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0007_auto_20210521_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
